---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "js/application.js"
  - "css/application.css"
